image: docker:stable
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - package
  - deploy
  - build-manual
  - package-manual
  - deploy-manual
  - backup

# Build stage
build:
  stage: build
  image: registry.gitlab.master.ssd.vps.vayetek.com/vayetek/devops/composer:1.10.19
  only:
    - master
    - develop
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    paths:
      - vendor/
    expire_in: 2 hours

build-feat:
  stage: build-manual
  image: registry.gitlab.master.ssd.vps.vayetek.com/vayetek/devops/composer:1.10.19
  when: manual
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    paths:
      - vendor/
    expire_in: 2 hours

# Package stage
docker-package:
  stage: package
  services:
    - docker:dind
  only:
    - master
    - develop
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  after_script:
    - docker logout "$CI_REGISTRY"
  script:
    - IMAGE_NAME="$CI_REGISTRY_IMAGE:app-$CI_COMMIT_REF_NAME"
    - docker build --pull -t "$IMAGE_NAME" -f docker/app.docker .
    - docker push "$IMAGE_NAME"
    - IMAGE_NAME="$CI_REGISTRY_IMAGE:web-$CI_COMMIT_REF_NAME"
    - docker build --pull -t "$IMAGE_NAME" -f docker/web.docker .
    - docker push "$IMAGE_NAME"

docker-package-feat:
  stage: package-manual
  services:
    - docker:dind
  when: manual
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  after_script:
    - docker logout "$CI_REGISTRY"
  script:
    - IMAGE_NAME="$CI_REGISTRY_IMAGE:app-feat"
    - docker build --pull -t "$IMAGE_NAME" -f docker/app.docker .
    - docker push "$IMAGE_NAME"
    - IMAGE_NAME="$CI_REGISTRY_IMAGE:web-feat"
    - docker build --pull -t "$IMAGE_NAME" -f docker/web.docker .
    - docker push "$IMAGE_NAME"


# Deploy stage
ansible-deploy-prod:
  stage: deploy
  image: mullnerz/ansible-playbook:2.9.1
  only:
    - master
  before_script:
    - chmod 600 $SSH_KEY
    - export APP_IMAGE_NAME="$CI_REGISTRY_IMAGE:app-$CI_COMMIT_REF_NAME"
    - export WEB_IMAGE_NAME="$CI_REGISTRY_IMAGE:web-$CI_COMMIT_REF_NAME"
    - export DEPLOY_TARGET=prod
    - cd ansible
  after_script:
    - cd ..
  script:
    - ansible-playbook --key-file $SSH_KEY playbook.yml

ansible-deploy-dev:
  stage: deploy
  image: mullnerz/ansible-playbook:2.9.1
  only:
    - develop
  before_script:
    - chmod 600 $SSH_KEY
    - export APP_IMAGE_NAME="$CI_REGISTRY_IMAGE:app-$CI_COMMIT_REF_NAME"
    - export WEB_IMAGE_NAME="$CI_REGISTRY_IMAGE:web-$CI_COMMIT_REF_NAME"
    - export DEPLOY_TARGET=dev
    - cd ansible
  after_script:
    - cd ..
  script:
    - ansible-playbook --key-file $SSH_KEY playbook.yml

# Deploy stage
ansible-deploy-prod-manual:
  stage: deploy-manual
  image: mullnerz/ansible-playbook:2.9.1
  when: manual
  only:
    - master
  before_script:
    - chmod 600 $SSH_KEY
    - export APP_IMAGE_NAME="$CI_REGISTRY_IMAGE:app-$CI_COMMIT_REF_NAME"
    - export WEB_IMAGE_NAME="$CI_REGISTRY_IMAGE:web-$CI_COMMIT_REF_NAME"
    - export DEPLOY_TARGET=prod
    - cd ansible
  after_script:
    - cd ..
  script:
    - ansible-playbook --key-file $SSH_KEY playbook.yml

ansible-deploy-dev-manual:
  stage: deploy-manual
  image: mullnerz/ansible-playbook:2.9.1
  when: manual
  only:
    - develop
  before_script:
    - chmod 600 $SSH_KEY
    - export APP_IMAGE_NAME="$CI_REGISTRY_IMAGE:app-$CI_COMMIT_REF_NAME"
    - export WEB_IMAGE_NAME="$CI_REGISTRY_IMAGE:web-$CI_COMMIT_REF_NAME"
    - export DEPLOY_TARGET=dev
    - cd ansible
  after_script:
    - cd ..
  script:
    - ansible-playbook --key-file $SSH_KEY playbook.yml

ansible-deploy-feat-manual:
  stage: deploy-manual
  image: mullnerz/ansible-playbook:2.9.1
  when: manual
  before_script:
    - chmod 600 $SSH_KEY
    - export APP_IMAGE_NAME="$CI_REGISTRY_IMAGE:app-feat"
    - export WEB_IMAGE_NAME="$CI_REGISTRY_IMAGE:web-feat"
    - export DEPLOY_TARGET=feat
    - export CI_COMMIT_REF_NAME=feat
    - cd ansible
  after_script:
    - cd ..
  script:
    - ansible-playbook --key-file $SSH_KEY playbook.yml

# Backup stages
backup-bitbucket:
  stage: backup
  image: registry.gitlab.master.ssd.vps.vayetek.com/vayetek/devops/git:master
  only:
    - master
    - develop
  before_script:
    - git checkout $CI_COMMIT_REF_NAME
    - git pull
    - eval $(ssh-agent -s)
    - ssh-add -D
    - chmod 600 $BITBUCKET_RSA
    - ssh-add $BITBUCKET_RSA
    - ssh git@bitbucket.com
  script:
    - git remote add bitbucket git@bitbucket.org:vayetek/congress-backend-modules.git
    - git push bitbucket $CI_COMMIT_REF_NAME
  after_script:
    - git remote remove bitbucket
    - ssh-add -D
