version: '2'
services:
    web:
        container_name: eventizer-api-web
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ./:/var/www
        links:
            - app
        environment:
            VIRTUAL_HOST: eventizer-api.vayetek.com,api.eventizer.io
            LETSENCRYPT_HOST: eventizer-api.vayetek.com,api.eventizer.io
            LETSENCRYPT_EMAIL: vayetek@gmail.com
    app:
        container_name: eventizer-api-app
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ./:/var/www
            - ../../data/eventizer_data:/var/www/storage/app
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        env_file: .env


networks:
  default:
    external:
      name: nginx-proxy
