---

- name: Login docker
  docker_login:
    registry_url: "{{ lookup('env','CI_REGISTRY') }}"
    username: "{{ lookup('env','CI_REGISTRY_USER') }}"
    password: "{{ lookup('env','CI_JOB_TOKEN') }}"
    state: "present"

- name: Create Eventizer API data directory
  file:
    path: "{{ eventizer_dir }}/data"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  become: true

- name: Copy .env
  copy:
    src: "{{ eventizer_env_file }}"
    dest: "{{ eventizer_dir }}/.env"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  become: true

- name: Run Eventizer API
  docker_compose:
    project_name: "eventizer-api-{{eventizer_version}}"
    definition:
      version: '3.7'
      services:
        web:
          image: "{{ lookup('env','WEB_IMAGE_NAME') }}"
          container_name: "eventizer-api-{{eventizer_version}}-web"
          restart: always
          links:
            - app
          environment:
            VIRTUAL_HOST: "{{ host_name }}"
            LETSENCRYPT_HOST: "{{ host_name }}"
            LETSENCRYPT_EMAIL: "{{ letsencrypt_email }}"
        app:
          image: "{{ lookup('env','APP_IMAGE_NAME') }}"
          container_name: "eventizer-api-{{eventizer_version}}-app"
          restart: always
          volumes:
            - "{{ eventizer_dir }}/.env:/var/www/.env"
            - "{{ eventizer_dir }}/data:/var/www/storage/app"
          env_file: "{{ eventizer_dir }}/.env"

      networks:
        default:
          external:
            name: "{{ docker_network }}"
  notify: Log out of DockerHub

- name: Sleep for 5 seconds
  wait_for:
    timeout: 5

- name: Change Dir Permission
  command: docker exec eventizer-api-{{ eventizer_version }}-app chown -R www-data.www-data .

- name: Change Dir Permission
  command: docker exec eventizer-api-{{ eventizer_version }}-app chmod -R 755 .

- name: Change Dir Permission
  command:  docker exec eventizer-api-{{ eventizer_version }}-app chmod -R 777 ./app

- name: Change Dir Permission
  command: docker exec eventizer-api-{{ eventizer_version }}-app chmod -R 777 ./vendor

- name: Change Dir Permission
  command:   docker exec eventizer-api-{{ eventizer_version }}-app php artisan key:generate
