INSERT INTO  Currency (code, label) VALUES ('AED','United Arab Emirates dirham');
INSERT INTO  Currency (code, label) VALUES ('AFN','Afghan afghani');
INSERT INTO  Currency (code, label) VALUES ('ALL','Albanian lek');
INSERT INTO  Currency (code, label) VALUES ('AMD','Armenian dram');
INSERT INTO  Currency (code, label) VALUES ('ANG','Netherlands Antillean guilder');
INSERT INTO  Currency (code, label) VALUES ('AOA','Angolan kwanza');
INSERT INTO  Currency (code, label) VALUES ('ARS','Argentine peso');
INSERT INTO  Currency (code, label) VALUES ('AUD','Australian dollar');
INSERT INTO  Currency (code, label) VALUES ('AWG','Aruban florin');
INSERT INTO  Currency (code, label) VALUES ('AZN','Azerbaijani manat');
INSERT INTO  Currency (code, label) VALUES ('BAM','Bosnia and Herzegovina convertible mark');
INSERT INTO  Currency (code, label) VALUES ('BBD','Barbados dollar');
INSERT INTO  Currency (code, label) VALUES ('BDT','Bangladeshi taka');
INSERT INTO  Currency (code, label) VALUES ('BGN','Bulgarian lev');
INSERT INTO  Currency (code, label) VALUES ('BHD','Bahraini dinar');
INSERT INTO  Currency (code, label) VALUES ('BIF','Burundian franc');
INSERT INTO  Currency (code, label) VALUES ('BMD','Bermudian dollar');
INSERT INTO  Currency (code, label) VALUES ('BND','Brunei dollar');
INSERT INTO  Currency (code, label) VALUES ('BOB','Boliviano');
INSERT INTO  Currency (code, label) VALUES ('BOV','Bolivian Mvdol (funds code)');
INSERT INTO  Currency (code, label) VALUES ('BRL','Brazilian real');
INSERT INTO  Currency (code, label) VALUES ('BSD','Bahamian dollar');
INSERT INTO  Currency (code, label) VALUES ('BTN','Bhutanese ngultrum');
INSERT INTO  Currency (code, label) VALUES ('BWP','Botswana pula');
INSERT INTO  Currency (code, label) VALUES ('BYR','Belarusian ruble');
INSERT INTO  Currency (code, label) VALUES ('BZD','Belize dollar');
INSERT INTO  Currency (code, label) VALUES ('CAD','Canadian dollar');
INSERT INTO  Currency (code, label) VALUES ('CDF','Congolese franc');
INSERT INTO  Currency (code, label) VALUES ('CHE','WIR Euro (complementary currency)');
INSERT INTO  Currency (code, label) VALUES ('CHF','Swiss franc');
INSERT INTO  Currency (code, label) VALUES ('CHW','WIR Franc (complementary currency)');
INSERT INTO  Currency (code, label) VALUES ('CLF','Unidad de Fomento (funds code)');
INSERT INTO  Currency (code, label) VALUES ('CLP','Chilean peso');
INSERT INTO  Currency (code, label) VALUES ('CNY','Chinese yuan');
INSERT INTO  Currency (code, label) VALUES ('COP','Colombian peso');
INSERT INTO  Currency (code, label) VALUES ('COU','Unidad de Valor Real');
INSERT INTO  Currency (code, label) VALUES ('CRC','Costa Rican colon');
INSERT INTO  Currency (code, label) VALUES ('CUC','Cuban convertible peso');
INSERT INTO  Currency (code, label) VALUES ('CUP','Cuban peso');
INSERT INTO  Currency (code, label) VALUES ('CVE','Cape Verde escudo');
INSERT INTO  Currency (code, label) VALUES ('CZK','Czech koruna');
INSERT INTO  Currency (code, label) VALUES ('DJF','Djiboutian franc');
INSERT INTO  Currency (code, label) VALUES ('DKK','Danish krone');
INSERT INTO  Currency (code, label) VALUES ('DOP','Dominican peso');
INSERT INTO  Currency (code, label) VALUES ('DZD','Algerian dinar');
INSERT INTO  Currency (code, label) VALUES ('EGP','Egyptian pound');
INSERT INTO  Currency (code, label) VALUES ('ERN','Eritrean nakfa');
INSERT INTO  Currency (code, label) VALUES ('ETB','Ethiopian birr');
INSERT INTO  Currency (code, label) VALUES ('EUR','Euro');
INSERT INTO  Currency (code, label) VALUES ('FJD','Fiji dollar');
INSERT INTO  Currency (code, label) VALUES ('FKP','Falkland Islands pound');
INSERT INTO  Currency (code, label) VALUES ('GBP','Pound sterling');
INSERT INTO  Currency (code, label) VALUES ('GEL','Georgian lari');
INSERT INTO  Currency (code, label) VALUES ('GHS','Ghanaian cedi');
INSERT INTO  Currency (code, label) VALUES ('GIP','Gibraltar pound');
INSERT INTO  Currency (code, label) VALUES ('GMD','Gambian dalasi');
INSERT INTO  Currency (code, label) VALUES ('GNF','Guinean franc');
INSERT INTO  Currency (code, label) VALUES ('GTQ','Guatemalan quetzal');
INSERT INTO  Currency (code, label) VALUES ('GYD','Guyanese dollar');
INSERT INTO  Currency (code, label) VALUES ('HKD','Hong Kong dollar');
INSERT INTO  Currency (code, label) VALUES ('HNL','Honduran lempira');
INSERT INTO  Currency (code, label) VALUES ('HRK','Croatian kuna');
INSERT INTO  Currency (code, label) VALUES ('HTG','Haitian gourde');
INSERT INTO  Currency (code, label) VALUES ('HUF','Hungarian forint');
INSERT INTO  Currency (code, label) VALUES ('IDR','Indonesian rupiah');
INSERT INTO  Currency (code, label) VALUES ('ILS','Israeli new shekel');
INSERT INTO  Currency (code, label) VALUES ('INR','Indian rupee');
INSERT INTO  Currency (code, label) VALUES ('IQD','Iraqi dinar');
INSERT INTO  Currency (code, label) VALUES ('IRR','Iranian rial');
INSERT INTO  Currency (code, label) VALUES ('ISK','Icelandic króna');
INSERT INTO  Currency (code, label) VALUES ('JMD','Jamaican dollar');
INSERT INTO  Currency (code, label) VALUES ('JOD','Jordanian dinar');
INSERT INTO  Currency (code, label) VALUES ('JPY','Japanese yen');
INSERT INTO  Currency (code, label) VALUES ('KES','Kenyan shilling');
INSERT INTO  Currency (code, label) VALUES ('KGS','Kyrgyzstani som');
INSERT INTO  Currency (code, label) VALUES ('KHR','Cambodian riel');
INSERT INTO  Currency (code, label) VALUES ('KMF','Comoro franc');
INSERT INTO  Currency (code, label) VALUES ('KPW','North Korean won');
INSERT INTO  Currency (code, label) VALUES ('KRW','South Korean won');
INSERT INTO  Currency (code, label) VALUES ('KWD','Kuwaiti dinar');
INSERT INTO  Currency (code, label) VALUES ('KYD','Cayman Islands dollar');
INSERT INTO  Currency (code, label) VALUES ('KZT','Kazakhstani tenge');
INSERT INTO  Currency (code, label) VALUES ('LAK','Lao kip');
INSERT INTO  Currency (code, label) VALUES ('LBP','Lebanese pound');
INSERT INTO  Currency (code, label) VALUES ('LKR','Sri Lankan rupee');
INSERT INTO  Currency (code, label) VALUES ('LRD','Liberian dollar');
INSERT INTO  Currency (code, label) VALUES ('LSL','Lesotho loti');
INSERT INTO  Currency (code, label) VALUES ('LTL','Lithuanian litas');
INSERT INTO  Currency (code, label) VALUES ('LVL','Latvian lats');
INSERT INTO  Currency (code, label) VALUES ('LYD','Libyan dinar');
INSERT INTO  Currency (code, label) VALUES ('MAD','Moroccan dirham');
INSERT INTO  Currency (code, label) VALUES ('MDL','Moldovan leu');
INSERT INTO  Currency (code, label) VALUES ('MGA','Malagasy ariary');
INSERT INTO  Currency (code, label) VALUES ('MKD','Macedonian denar');
INSERT INTO  Currency (code, label) VALUES ('MMK','Myanma kyat');
INSERT INTO  Currency (code, label) VALUES ('MNT','Mongolian tugrik');
INSERT INTO  Currency (code, label) VALUES ('MOP','Macanese pataca');
INSERT INTO  Currency (code, label) VALUES ('MRO','Mauritanian ouguiya');
INSERT INTO  Currency (code, label) VALUES ('MUR','Mauritian rupee');
INSERT INTO  Currency (code, label) VALUES ('MVR','Maldivian rufiyaa');
INSERT INTO  Currency (code, label) VALUES ('MWK','Malawian kwacha');
INSERT INTO  Currency (code, label) VALUES ('MXN','Mexican peso');
INSERT INTO  Currency (code, label) VALUES ('MXV','Mexican Unidad de Inversion (UDI) (funds code)');
INSERT INTO  Currency (code, label) VALUES ('MYR','Malaysian ringgit');
INSERT INTO  Currency (code, label) VALUES ('MZN','Mozambican metical');
INSERT INTO  Currency (code, label) VALUES ('NAD','Namibian dollar');
INSERT INTO  Currency (code, label) VALUES ('NGN','Nigerian naira');
INSERT INTO  Currency (code, label) VALUES ('NIO','Nicaraguan córdoba');
INSERT INTO  Currency (code, label) VALUES ('NOK','Norwegian krone');
INSERT INTO  Currency (code, label) VALUES ('NPR','Nepalese rupee');
INSERT INTO  Currency (code, label) VALUES ('NZD','New Zealand dollar');
INSERT INTO  Currency (code, label) VALUES ('OMR','Omani rial');
INSERT INTO  Currency (code, label) VALUES ('PAB','Panamanian balboa');
INSERT INTO  Currency (code, label) VALUES ('PEN','Peruvian nuevo sol');
INSERT INTO  Currency (code, label) VALUES ('PGK','Papua New Guinean kina');
INSERT INTO  Currency (code, label) VALUES ('PHP','Philippine peso');
INSERT INTO  Currency (code, label) VALUES ('PKR','Pakistani rupee');
INSERT INTO  Currency (code, label) VALUES ('PLN','Polish złoty');
INSERT INTO  Currency (code, label) VALUES ('PYG','Paraguayan guaraní');
INSERT INTO  Currency (code, label) VALUES ('QAR','Qatari riyal');
INSERT INTO  Currency (code, label) VALUES ('RON','Romanian new leu');
INSERT INTO  Currency (code, label) VALUES ('RSD','Serbian dinar');
INSERT INTO  Currency (code, label) VALUES ('RUB','Russian rouble');
INSERT INTO  Currency (code, label) VALUES ('RWF','Rwandan franc');
INSERT INTO  Currency (code, label) VALUES ('SAR','Saudi riyal');
INSERT INTO  Currency (code, label) VALUES ('SBD','Solomon Islands dollar');
INSERT INTO  Currency (code, label) VALUES ('SCR','Seychelles rupee');
INSERT INTO  Currency (code, label) VALUES ('SDG','Sudanese pound');
INSERT INTO  Currency (code, label) VALUES ('SEK','Swedish krona/kronor');
INSERT INTO  Currency (code, label) VALUES ('SGD','Singapore dollar');
INSERT INTO  Currency (code, label) VALUES ('SHP','Saint Helena pound');
INSERT INTO  Currency (code, label) VALUES ('SLL','Sierra Leonean leone');
INSERT INTO  Currency (code, label) VALUES ('SOS','Somali shilling');
INSERT INTO  Currency (code, label) VALUES ('SRD','Surinamese dollar');
INSERT INTO  Currency (code, label) VALUES ('SSP','South Sudanese pound');
INSERT INTO  Currency (code, label) VALUES ('STD','São Tomé and Príncipe dobra');
INSERT INTO  Currency (code, label) VALUES ('SYP','Syrian pound');
INSERT INTO  Currency (code, label) VALUES ('SZL','Swazi lilangeni');
INSERT INTO  Currency (code, label) VALUES ('THB','Thai baht');
INSERT INTO  Currency (code, label) VALUES ('TJS','Tajikistani somoni');
INSERT INTO  Currency (code, label) VALUES ('TMT','Turkmenistani manat');
INSERT INTO  Currency (code, label) VALUES ('TND','Tunisian dinar');
INSERT INTO  Currency (code, label) VALUES ('TOP','Tongan paʻanga');
INSERT INTO  Currency (code, label) VALUES ('TRY','Turkish lira');
INSERT INTO  Currency (code, label) VALUES ('TTD','Trinidad and Tobago dollar');
INSERT INTO  Currency (code, label) VALUES ('TWD','New Taiwan dollar');
INSERT INTO  Currency (code, label) VALUES ('TZS','Tanzanian shilling');
INSERT INTO  Currency (code, label) VALUES ('UAH','Ukrainian hryvnia');
INSERT INTO  Currency (code, label) VALUES ('UGX','Ugandan shilling');
INSERT INTO  Currency (code, label) VALUES ('USD','United States dollar');
INSERT INTO  Currency (code, label) VALUES ('UYU','Uruguayan peso');
INSERT INTO  Currency (code, label) VALUES ('UZS','Uzbekistan som');
INSERT INTO  Currency (code, label) VALUES ('VEF','Venezuelan bolívar fuerte');
INSERT INTO  Currency (code, label) VALUES ('VND','Vietnamese dong');
INSERT INTO  Currency (code, label) VALUES ('VUV','Vanuatu vatu');
INSERT INTO  Currency (code, label) VALUES ('WST','Samoan tala');
INSERT INTO  Currency (code, label) VALUES ('XAF','CFA franc BEAC');
INSERT INTO  Currency (code, label) VALUES ('XCD','East Caribbean dollar');
INSERT INTO  Currency (code, label) VALUES ('YER','Yemeni rial');
INSERT INTO  Currency (code, label) VALUES ('ZAR','South African rand');
INSERT INTO  Currency (code, label) VALUES ('ZMW','Zambian kwacha');
