INSERT INTO  Currency (code, label) VALUES ('TND','Tunisian dinar');
INSERT INTO  Currency (code, label) VALUES ('EUR','Euro');
INSERT INTO  Currency (code, label) VALUES ('USD','United States dollar');
INSERT INTO  Currency (code, label) VALUES ('CAD','Canadian dollar');
INSERT INTO  Currency (code, label) VALUES ('HKD','Hong Kong dollar');
INSERT INTO  Currency (code, label) VALUES ('ISK','Icelandic króna');
INSERT INTO  Currency (code, label) VALUES ('PHP','Philippine peso');
INSERT INTO  Currency (code, label) VALUES ('DKK','Danish krone');
INSERT INTO  Currency (code, label) VALUES ('HUF','Hungarian forint');
INSERT INTO  Currency (code, label) VALUES ('CZK','Czech koruna');
INSERT INTO  Currency (code, label) VALUES ('AUD','Australian dollar');
INSERT INTO  Currency (code, label) VALUES ('RON','Romanian new leu');
INSERT INTO  Currency (code, label) VALUES ('SEK','Swedish krona/kronor');
INSERT INTO  Currency (code, label) VALUES ('IDR','Indonesian rupiah');
INSERT INTO  Currency (code, label) VALUES ('INR','Indian rupee');
INSERT INTO  Currency (code, label) VALUES ('BRL','Brazilian real');
INSERT INTO  Currency (code, label) VALUES ('RUB','Russian rouble');
INSERT INTO  Currency (code, label) VALUES ('HRK','Croatian kuna');
INSERT INTO  Currency (code, label) VALUES ('JPY','Japanese yen');
INSERT INTO  Currency (code, label) VALUES ('THB','Thai baht');
INSERT INTO  Currency (code, label) VALUES ('CHF','Swiss franc');
INSERT INTO  Currency (code, label) VALUES ('SGD','Singapore dollar');
INSERT INTO  Currency (code, label) VALUES ('PLN','Polish złoty');
INSERT INTO  Currency (code, label) VALUES ('BGN','Bulgarian lev');
INSERT INTO  Currency (code, label) VALUES ('TRY','Turkish lira');
INSERT INTO  Currency (code, label) VALUES ('CNY','Chinese yuan');
INSERT INTO  Currency (code, label) VALUES ('NOK','Norwegian krone');
INSERT INTO  Currency (code, label) VALUES ('NZD','New Zealand dollar');
INSERT INTO  Currency (code, label) VALUES ('ZAR','South African rand');
INSERT INTO  Currency (code, label) VALUES ('MXN','Mexican peso');
INSERT INTO  Currency (code, label) VALUES ('ILS','Israeli new shekel');
INSERT INTO  Currency (code, label) VALUES ('GBP','Pound sterling');
INSERT INTO  Currency (code, label) VALUES ('KRW','South Korean won');
INSERT INTO  Currency (code, label) VALUES ('MYR','Malaysian ringgit');
INSERT INTO  Currency (code, label) VALUES ('AED','United Arab Emirates dirham');
INSERT INTO  Currency (code, label) VALUES ('BHD','Bahraini dinar');
INSERT INTO  Currency (code, label) VALUES ('EGP','Egyptian pound');
INSERT INTO  Currency (code, label) VALUES ('DZD','Algerian dinar');
INSERT INTO  Currency (code, label) VALUES ('IQD','Iraqi dinar');
INSERT INTO  Currency (code, label) VALUES ('IRR','Iranian rial');
INSERT INTO  Currency (code, label) VALUES ('JOD','Jordanian dinar');
INSERT INTO  Currency (code, label) VALUES ('KPW','North Korean won');
INSERT INTO  Currency (code, label) VALUES ('KWD','Kuwaiti dinar');
INSERT INTO  Currency (code, label) VALUES ('LBP','Lebanese pound');
INSERT INTO  Currency (code, label) VALUES ('LYD','Libyan dinar');
INSERT INTO  Currency (code, label) VALUES ('MAD','Moroccan dirham');
INSERT INTO  Currency (code, label) VALUES ('NGN','Nigerian naira');
INSERT INTO  Currency (code, label) VALUES ('OMR','Omani rial');
INSERT INTO  Currency (code, label) VALUES ('QAR','Qatari riyal');
INSERT INTO  Currency (code, label) VALUES ('RSD','Serbian dinar');
INSERT INTO  Currency (code, label) VALUES ('SAR','Saudi riyal');
INSERT INTO  Currency (code, label) VALUES ('RWF','Rwandan franc');
INSERT INTO  Currency (code, label) VALUES ('SYP','Syrian pound');
INSERT INTO  Currency (code, label) VALUES ('YER','Yemeni rial');
