INSERT INTO `Etablissement`
(`city`, `label`) VALUES
("Tunis","Centre d''Assistance Médicale Urgente")
,("","Centre de Maternité et de Néonatologie de Tunis")
,("","Centre National de Greffe de Moëlle Osseuse")
,("","Centre National de Pharmacovigilance Chalbi Belkahia ")
,("","Direction Générale de la Santé Militaire")
,("","Faculté de Médecine de Tunis")
,("","Hôpital Aziza Othmana")
,("","Hôpital Charles Nicolle")
,("","Hôpital d''enfants Béchir Hamza ")
,("","Hôpital Habib Thameur")
,("","Hôpital La Rabta")
,("","Hôpital Militaire Principal d''Instruction de Tunis")
,("","Institut de Santé et Sécurité de Travail")
,("","Institut Hédi Raïes d''Ophtalmologie ")
,("","Institut National de Santé")
,("","Institut National Mongi Ben Hmida de Neurologie")
,("","Institut National de Nutrition et de Technologie Alimentaire")
,("","Institut Pasteur")
,("","Institut Salah Azaiez")
,("","Service d''Aide Médicale Urgente")
,("Ariana","Hôpital Abderrahmen Mami de Pneumologie ")
,("","Hôpital Régional Mahmoud El Matri")
,("Manouba","Institut Mohamed Kassab d''Orthopédie")
,("","Hôpital Razi")
,("La Marsa","Hôpital des Forces de Sécurité Intérieure")
,("","Hôpital Mongi Slim")
,("Ben Arous","Centre de Traumatologie et des Grand Brûlés")
,("","Hôpital Régional Yesminet de Ben Arous")
,("Bizerte","Hôpital Militaire de Bizerte")
,("","Hôpital Régional de Menzel Bourguiba")
,("","Hôpital Régional Habib Bougatfa")
,("Nabeul","Hôpital Régional de Menzel Temime")
,("","Hôpital Régional Mohamed Tahar Maamouri ")
,("","Hôpital Régional Mohamed Tlatli ")
,("Béja","Hôpital Régional de Béja")
,("Jendouba","Hôpital Régional de Jendouba")
,("Zaghouane","Complexe de Jebel El Ouest")
,("","Hôpital Régional de Zaghouane")
,("Siliana","Hôpital Régional de Siliana")
,("Le Kef","Hôpital Régional Mhamed Bourguiba du Kef")
,("Sousse","Faculté de Médecine de Sousse")
,("","Hôpital Farhat Hached")
,("","Hôpital Sahloul ")
,("Monastir","Faculté de Médecine de Monastir ")
,("","Hôpital Fattouma Bourguiba de Monastir")
,("","Hôpital Régional Haj Ali Souaa de Ksar Hlel")
,("Mahdia","Hôpital Tahar Sfar de Mahdia")
,("Kairouan","Hôpital Régional Ibn Jazzar de Kairouan")
,("Kasserine","Hôpital Régional de Kasserine")
,("Sidi Bouzid","Hôpital Régional de Sidi Bouzid")
,("Sfax","Faculté de Médecine de Sfax")
,("","Hôpital Habib Bourguiba de Sfax")
,("","Hôpital Hédi Chaker de Sfax")
,("","Hôpital Régional de Mahrès")
,("Gafsa","Hôpital Régional de Gafsa")
,("Gabès","Hôpital Militaire de Gabès")
,("","Hôpital Régional Mohamed Ben Sassi de Gabès")
,("Medenine","Hôpital Régional de Medenine")
,("Tataouine","Hôpital Régional de Tataouine");
