INSERT INTO `Service`
 (`label`) VALUES
 ("Anatomie")
,("Anatomie et cytologie pathologiques")
,("Anesthésie réanimation")
,("Bactériologie")
,("Biochimie")
,("Biologie de la reproduction et cytogénétique")
,("Biologie médicale")
,("Biologie médicale et Banque du sang")
,("Carcinologie médicale")
,("Carcinologie médicale et Radiothérapie")
,("Cardiologie")
,("Cardiologie adulte")
,("Cardiologie pédiatrique")
,("Cardiologie: Urgences et explorations fonctionnelles")
,("Centre militaire d’hygiène et de protection de l’environnement")
,("Chirurgie carcinologique")
,("Chirurgie cardio-vasculaire")
,("Chirurgie cardio-vasculaire et thoracique")
,("Chirurgie générale")
,("Chirurgie générale (A 21)")
,("Chirurgie générale (B 23)")
,("Chirurgie maxillo-faciale")
,("Chirurgie neurologique")
,("Chirurgie orthopédique adulte")
,("Chirurgie orthopédique et traumatologique")
,("Chirurgie orthopédique infantile")
,("Chirurgie pédiatrique")
,("Chirurgie pédiatrique A")
,("Chirurgie pédiatrique B")
,("Chirurgie plastique, réparatrice et esthétique")
,("Chirurgie thoracique et cardio-vasculaire")
,("Chirurgie urologique")
,("Chirurgie vasculaire périphérique")
,("Consultations d'ophtalmologie")
,("Consultations externes et Urgence ")
,("Consultatios externes")
,("Cyto-génetique")
,("Dermatologie")
,("Endocrinologie")
,("Endocrinologie Nutrition (A)")
,("Endocrinologie Nutrition (B)")
,("Endocrinologie Nutrition (C)")
,("Explorations fonctionnelles du système nerveux")
,("Gastro-entérologie")
,("Gastro-entérologie A ")
,("Gastro-entérologie B ")
,("Génétique")
,("Gynécologie obstétrique (A)")
,("Gynécologie obstétrique (B)")
,("Gynécologie obstétrique (C)")
,("Gynécologie obstétrique (D)")
,("Gynécologie-obstétrique")
,("Gynécologie-obstétrique G25")
,("Gynécologie-obstétrique G26")
,("Gynécologie-obstétrique-Urgences")
,("Hématologie biologique")
,("Hématologie clinique")
,("Hématologie pédiatrique")
,("Hémodialyse")
,("Hygiène hospitalière")
,("Imagerie médicale")
,("Immunologie")
,("Laboratoire d'Histo-embryologie")
,("Maladies génétiques")
,("Maladies Infectieuses")
,("Médecine de travail")
,("Médecine interne")
,("Médecine interne A (M8)")
,("Médecine Interne B (10)")
,("Médecine légale")
,("Médecine nucléaire")
,("Médecine physique, rééducation et  réadaptation fonctionnelle")
,("Microbiologie")
,("Néonatologie")
,("Néphrologie")
,("Neurologie")
,("Neurologie pédiatrique")
,("Ophtalmologie")
,("Ophtalmologie (A)")
,("Ophtalmologie (B)")
,("Ophtalmologie (C)")
,("Oto-rhino-laryngologie")
,("Oto-rhino-laryngologie et chirurgie cervico-faciale")
,("Parasitologie")
,("Pédiatrie")
,("Pédiatrie A (3ème étage) ")
,("Pédiatrie B (4ème étage)")
,("Pédiatrie C (2éme étage) ")
,("Pédiatrie et néonatologie")
,("Pédiatrie: Urgences et consultations")
,("Pédo-psychiatrie")
,("Pharmacologie")
,("Pharmacologie clinique")
,("Physiologie et explorations fonctionnelles")
,("Physiothérapie et explorations fonctionnelles respiratoires")
,("Pneumologie")
,("Pneumologie (Ibn Nafis)")
,("Pneumologie (Pavillon 2)")
,("Pneumologie (Pavillon 2)")
,("Pneumologie (Pavillon 4)")
,("Pneumologie (Pavillon B)")
,("Pneumologie (Pavillon C)")
,("Pneumologie (Pavillon D)")
,("Psychiatrie")
,("Psychiatrie (A) - Ibn Sina")
,("Psychiatrie (B) - Pinell")
,("Psychiatrie (C ) - Kindy")
,("Psychiatrie (D) - Sfar")
,("Psychiatrie (E)  - Ibn Omrane")
,("Psychiatrie (F) - Aziza Othmana")
,("Psychiatrie (G) - Ibn Jazzar")
,("Psychiatrie Légale - Salem Eschadely")
,("Radiothérapie")
,("Réanimation cardiologique et Explorations fonctionnelles")
,("Réanimation des brûlés")
,("Réanimation médicale")
,("Réanimation pédiatrique")
,("Rhumatologie")
,("SAMU (01)")
,("SAMU (02)")
,("SAMU (03)")
,("Urgence")
,("Urgence chirurgicale")
,("Urgence orthopédique")
,("Urgence pédiatrique et Consultations externes")
,("Virologie")
